#!/usr/bin/env python3

import subprocess
from http.server import HTTPServer, SimpleHTTPRequestHandler


class RequestHandler(SimpleHTTPRequestHandler):
    def end_headers(self):
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Cross-Origin-Embedder-Policy", "require-corp")
        self.send_header("Cross-Origin-Opener-Policy", "same-origin")
        super().end_headers()


def main():
    subprocess.check_call(
        [
            "emcc",
            "-std=c++17",
            "-pthread",
            "-s",
            "PTHREAD_POOL_SIZE=2",
            "-s",
            "ENVIRONMENT=web,worker",
            "main.cc",
            "-o",
            "index.html",
        ]
    )

    addr = "127.0.0.1"
    port = 8080
    httpd = HTTPServer((addr, port), RequestHandler)
    print("Serving http at http://{}:{}".format(addr, port))

    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        print("\nBye.")


if __name__ == "__main__":
    main()
